### ISSUE TITLE
Will this be updated to support Sass module system?

### ISSUE THREAD

**Issue by kerryj89** [nicoespeon/sass-graph-viz#27]
I understand if this complication requires more time and effort than you have to spare.

- [@use](https://sass-lang.com/documentation/at-rules/use)
- [@forward](https://sass-lang.com/documentation/at-rules/forward)
- [@include meta.load-css()](https://sass-lang.com/documentation/modules/meta)

Thanks!

**Comment by nicoespeon** [comment]
Hey @kerryj89 !

I'm not really using this anymore, so I don't really have plans to update this. However, it sounds that could be solved by upgrading the `sass-graph` dependency (https://github.com/xzyfer/sass-graph). We use v3 and v4 have been released a few months ago. Maybe it supports Sass module system—if not, then I have no idea.

The project is well covered with tests. If you give it a try and open a PR, I will review it. I'm not sure that would work, but you could craft a toy example in the `examples/` folder, for instance.
